version: "3"

services:
  ih-aws-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: ih_aws_cli
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
